################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

################################################################################
#   CHANNEL Defaults
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Section: Organizations
################################################################################
Organizations:
    - &Orderer
      Name: OrdererMSP
      ID: OrdererMSP
      MSPDir: crypto-config/peerOrganizations/orderer.org/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('OrdererMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"

      AnchorPeers:

    - &Org1
      Name: Org1MSP
      ID: Org1MSP
      MSPDir: crypto-config/peerOrganizations/org1.co/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('Org1MSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('Org1MSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('Org1MSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('Org1MSP.member')"

      AnchorPeers:
          - Host: peer0.org1.co
            Port: 7041

    - &Org2
      Name: Org2MSP
      ID: Org2MSP
      MSPDir: crypto-config/peerOrganizations/org2.ac/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('Org2MSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('Org2MSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('Org2MSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('Org2MSP.member')"

      AnchorPeers:
          - Host: peer0.org2.ac
            Port: 7061

    - &Org3
      Name: Org3MSP
      ID: Org3MSP
      MSPDir: crypto-config/peerOrganizations/org3.gov/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('Org3MSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('Org3MSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('Org3MSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('Org3MSP.member')"

      AnchorPeers:
          - Host: peer0.org3.gov
            Port: 7081

    - &Owners
      Name: OwnersMSP
      ID: OwnersMSP
      MSPDir: crypto-config/peerOrganizations/owners.org/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('OwnersMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('OwnersMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('OwnersMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('OwnersMSP.member')"

      AnchorPeers:
          - Host: peer0.owners.org
            Port: 7101

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &AuthoritiesDefaults
    OrdererType: solo
    Addresses:
        - orderer0.authorities.orderer.org:7030
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

################################################################################
#   Profile
################################################################################
# https://github:com/hyperledger/fabric/blob/master/sampleconfig/configtx.yaml

Profiles:
    # Profile used to create Genesis block for group authorities #
    AuthoritiesGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *AuthoritiesDefaults
            Organizations:
                - *Orderer
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Orderer
                    - *Org1
                    - *Org2
                    - *Org3
                    - *Owners

    # Profile used to create channeltx for ch1 #
    Ch1:
        <<: *ChannelDefaults
        Orderer:
            <<: *AuthoritiesDefaults
            Organizations:
                - *Orderer
            Capabilities:
                <<: *ApplicationCapabilities
        Consortium: SampleConsortium
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
                    - *Org2
                    - *Org3
                    - *Owners
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
                - *Org3
                - *Owners
